name: Build and Archive APK

on: workflow_dispatch

env:
  MAVEN_OPTS: >-
    -Dmaven.wagon.httpconnectionManager.ttlSeconds=120

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: "18"
          distribution: "temurin"

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5

      - name: Execute Gradle build
        run: |
          # For debugging, an ephemeral key suffice
          keytool -genkey -v -keystore debug.keystore -storepass password -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000 -keypass password -dname "CN=Android Debug,O=Android,C=US"

          ./gradlew \
           -PDEBUG_STORE_FILE=debug.keystore \
           -PDEBUG_STORE_PASSWORD=password \
           -PDEBUG_KEY_ALIAS=androiddebugkey \
           -PDEBUG_KEY_PASSWORD=password \
           -PIS_NEXT=true \
           assembleDebug

      - name: Archive APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: "${{ github.workspace }}/app/build/outputs/apk/debug/app-debug.apk"
